### ISSUE TITLE
Specify the network in the examples

### ISSUE THREAD

**Issue by ungarson** [madfish-solutions/quipuswap-sdk#4]
Hi, would be cool if you could specify networks used in the examples (README.md), for example in the `Get token price ` example you've used florencenet, but it's not specified.
Why? Because right now it's not clear if the mainnet is used and you just made a typo in the contracts addresses, or if it's some other network.

**Comment by atomantic** [comment]
It would also be great if you could point to where to find the `mainnet` factories. If you point to a mainnet node and then run the sample, you get an error:

```
HttpResponseError {
  message: 'Http error response: (404) ',
  status: 404,
  statusText: 'Not Found',
  body: '',
  url: 'https://mainnet.smartpy.io/chains/main/blocks/head/context/contracts/KT1Bps1VtszT2T3Yvxm5PJ6Rx2nk1FykWPdU/script',
  name: 'HttpResponse'
}
```

but I don't know where to find the correct `fa1_2Factory` and `fa2Factory` for mainnet...

**Comment by atomantic** [comment]
Also good to know that you can specify multiple factories. Found this in the Discord server and it works for mainnet: 

```
const factories = {
  fa1_2Factory: [
    'KT1Lw8hCoaBrHeTeMXbqHPG4sS4K1xn7yKcD',
    'KT1FWHLMk5tHbwuSsp31S4Jum4dTVmkXpfJw',
  ],
  fa2Factory: [
    'KT1SwH9P1Tx8a58Mm6qBExQFTcy2rwZyZiXS',
    'KT1PvEyN1xCFCgorN92QCfYjw3axS6jawCiJ',
  ],
};
```
